# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
    -   id: flake8
        additional_dependencies:
        -    flake8-typing-imports==1.14.0
        language_version: python3
        exclude: "^(build|docs|tests|setup.py)"
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v0.931'
#     hooks:
#     -   id: mypy
#         additional_dependencies: ["pydantic"]
#         exclude: "^(build|docs|tests|setup.py)"
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py37-plus, --keep-runtime-typing]
