# Development environment for pado
name: pado

channels:
  - conda-forge
  - defaults

dependencies:
  # python relevant things
  - python>=3.6
  - pip
  - typing_extensions
  - importlib_resources
  - setuptools_scm

  # pado requirements
  - toml
  - tqdm
  - pyarrow
  - numpy
  - pandas
  - shapely

  # support for pado.ext.testsource
  - tifffile


  - JPype1>=1

  # testing relevant things
  - pytest>=6
  - pytest-cov

  # pip installs
  - pip:
    - "-e ."
