# Development environment for pado
name: pado

channels:
  - conda-forge
  - defaults

dependencies:
  - python>=3.8
  - pip
  - pandas
  - jpype1>=1.0.1
  - pyarrow
  - tifffile
  - numpy
  - toml
  - importlib_resources
  - pytest>=6
  - pytest-cov

  - pip:
    - dynaconf>=3,!=3.1.0
    - "-e ."
