# Development environment for pado
name: pado

channels:
  - conda-forge
  - sdvillal
  - defaults

dependencies:
  - python>=3.8
  - pip
  - pycrypto
  - paramiko
  - pandas

  # styleframe
  - openpyxl>=2.5,<3.0.5  # this should be unpinned, but styleframe is not in conda
  - colour>=0.1.5,<0.2
  - jsonschema
  - xlrd>=1.0.0,<1.3.0

  - joblib
  - pysmb
  - argh

  - jpype1>=1.0.1
  - pyarrow

  - cryptography
  - fuzzywuzzy

  - importlib_resources

  # - qupath
  - pip:
    - styleframe
    # - "-e ."
