#
# Conda devenv environment for pado
#
# Create the environment, do not install pado in development mode:
#   conda devenv
# equivalent to:
#   PADO_DEVEL="" conda devenv
# Create the environment, install pado in development mode:
#   PADO_DEVEL=TRUE conda devenv
#

{% set PADO_DEVEL = os.environ.get('PADO_DEVEL', False) %}
{% set PADO_DEVEL_CI = os.environ.get('PADO_DEVEL_CI', False) %}

name: pado

channels:
  - conda-forge

dependencies:
  # python relevant things
  - python>=3.6
  - pip
  - typing_extensions
  - importlib_resources
  - setuptools_scm

  # pado requirements
  - appdirs
  - orjson
  - fsspec
  - toml
  - tqdm
  - pyarrow
  - numpy
  - pandas
  - shapely

  # support for pado.ext.testsource
  - tifffile

  # testing relevant things
  - pytest>=6
  - pytest-cov

  # pip installs
  - pip:      # [ PADO_DEVEL or PADO_DEVEL_CI ]
    - "git+https://github.com/Bayer-Group/tiffslide.git#egg=tiffslide"  # [ PADO_DEVEL_CI ]
    - "-e ."  # [ PADO_DEVEL ]
